// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

type ZoneCreateConfigType string

const (
	ZoneCreateConfigTypeZoneVcenterConfig ZoneCreateConfigType = "zoneVcenterConfig"
)

type ZoneCreateConfig struct {
	ZoneVcenterConfig *ZoneVcenterConfig

	Type ZoneCreateConfigType
}

func CreateZoneCreateConfigZoneVcenterConfig(zoneVcenterConfig ZoneVcenterConfig) ZoneCreateConfig {
	typ := ZoneCreateConfigTypeZoneVcenterConfig

	return ZoneCreateConfig{
		ZoneVcenterConfig: &zoneVcenterConfig,
		Type:              typ,
	}
}

func (u *ZoneCreateConfig) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	zoneVcenterConfig := new(ZoneVcenterConfig)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&zoneVcenterConfig); err == nil {
		u.ZoneVcenterConfig = zoneVcenterConfig
		u.Type = ZoneCreateConfigTypeZoneVcenterConfig
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ZoneCreateConfig) MarshalJSON() ([]byte, error) {
	if u.ZoneVcenterConfig != nil {
		return json.Marshal(u.ZoneVcenterConfig)
	}

	return nil, nil
}

// ZoneCreateCredential - Map containing Credential ID. Setting `type` to `local` means use the values set in the local cloud config instead of associating a credential.
type ZoneCreateCredential struct {
	ID *int64 `json:"id,omitempty"`
}

// ZoneCreateVisibility - private or public
type ZoneCreateVisibility string

const (
	ZoneCreateVisibilityPrivate ZoneCreateVisibility = "private"
	ZoneCreateVisibilityPublic  ZoneCreateVisibility = "public"
)

func (e ZoneCreateVisibility) ToPointer() *ZoneCreateVisibility {
	return &e
}

func (e *ZoneCreateVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private":
		fallthrough
	case "public":
		*e = ZoneCreateVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ZoneCreateVisibility: %v", v)
	}
}

// ZoneCreateZoneType - Map containing the Cloud (zone) code name. See the zone-types API to fetch a list of all available Cloud (zone) types and their codes.
type ZoneCreateZoneType struct {
	Code *string `json:"code,omitempty"`
}

type ZoneCreate struct {
	// Specifies which Tenant this cloud should be assigned to
	AccountID *int64 `json:"accountId,omitempty"`
	// Optional code for use with policies
	Code   *string           `json:"code,omitempty"`
	Config *ZoneCreateConfig `json:"config,omitempty"`
	// Map containing Credential ID. Setting `type` to `local` means use the values set in the local cloud config instead of associating a credential.
	Credential *ZoneCreateCredential `json:"credential,omitempty"`
	// Optional description field if you want to put more info there
	Description *string `json:"description,omitempty"`
	// Can be used to disable the cloud
	Enabled *bool `json:"enabled,omitempty"`
	// Specifies which Server group this cloud should be assigned to
	GroupID int64 `json:"groupId"`
	// A unique name scoped to your account for the cloud
	Name string `json:"name"`
	// Scale Priority
	ScalePriority *int64 `json:"scalePriority,omitempty"`
	// private or public
	Visibility *ZoneCreateVisibility `json:"visibility,omitempty"`
	// Map containing the Cloud (zone) code name. See the zone-types API to fetch a list of all available Cloud (zone) types and their codes.
	ZoneType ZoneCreateZoneType `json:"zoneType"`
}
