// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ZoneVcenterConfig struct {
	APIURL       *string `json:"apiUrl,omitempty"`
	ApplianceURL *string `json:"applianceUrl,omitempty"`
	Datacenter   *string `json:"datacenter,omitempty"`
}
