// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MyTest/internal/sdk/pkg/models/shared"
	"net/http"
)

type AddCloudsRequestBody struct {
	Zone shared.ZoneCreate `json:"zone"`
}

// AddClouds200ApplicationJSON - Successful Request
type AddClouds200ApplicationJSON struct {
	Zone *shared.Zone `json:"zone,omitempty"`
}

type AddCloudsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Request
	AddClouds200ApplicationJSONObject *AddClouds200ApplicationJSON
	// Error Codes
	DefaultError *shared.DefaultError
}
