// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MyTest/internal/sdk/pkg/models/shared"
	"net/http"
)

type AddCloudsRequestBody struct {
	Zone shared.ZoneCreate `json:"zone"`
}

// AddClouds200ApplicationJSON - Successful Request
type AddClouds200ApplicationJSON struct {
	Zone *shared.Zone `json:"zone,omitempty"`
}

type AddCloudsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful Request
	AddClouds200ApplicationJSONObject *AddClouds200ApplicationJSON
	// Error Codes
	DefaultError *shared.DefaultError
}
