// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MyTest/internal/sdk/pkg/models/shared"
	"net/http"
)

type RemoveCloudsRequest struct {
	// Morpheus ID of the Object being referenced
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type RemoveCloudsResponse struct {
	// Successful Request
	TwoHundredSuccess *shared.TwoHundredSuccess
	ContentType       string
	StatusCode        int
	RawResponse       *http.Response
	// Error Codes
	DefaultError *shared.DefaultError
}
